version: "3"
services:
  web:
    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/myapp
      - ~/.ssh:/root/.ssh
      - gemfiles:/usr/local/bundle
    ports:
      - "3000:3000"
volumes:
  gemfiles:

